# Needed for Metal, the hardware acceleration api for osx
MACOSX_SDK_VERSION:        # [osx]
  - "13.3"                 # [osx]

# Use the same version specified in https://github.com/rerun-io/rerun/blob/0.24.0/rust-toolchain#L8
# (or the similar file in the current version)
rust_compiler_version:
  - 1.88.0
