{% set name = "rerun-sdk" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rerun-io/rerun/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2b45114492618460a0594fd11eb221a9258fd6828439d2caaea42b567b5dee1e


build:
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - crossenv                               # [build_platform != target_platform]
    - maturin >=0.14,<0.15                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
    # Not using the conda compiler as its version was to low
    - rust >=1.67.1
    - rust-std-wasm32-unknown-unknown
    {% if target_platform == "osx-arm64" %}
    - rust-std-aarch64-apple-darwin
    {% endif %}
    - semver >=2.13,<2.14
    - wheel >=0.38,<0.39
    - pytest
    - binaryen
  host:
    - pip
    - python
    - maturin
  run:
    - python
    - attrs >=23.1.0
    - deprecated
    - numpy >=1.23
    - pillow
    - pyarrow ==10.0.1
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("11") }}  # [osx]

test:
  imports:
    - rerun_sdk
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.rerun.io/
  summary: Rerun is an SDK for logging computer vision and robotics data paired with a visualizer for exploring that data over time.
  description: |
    Rerun is an SDK for logging computer vision and robotics data paired with a visualizer for exploring that data over time. 
    It lets you debug and understand the internal state and data of your systems with minimal code.
  license: MIT OR Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE-MIT
    - LICENSE-APACHE

  doc_url: https://www.rerun.io/docs
  dev_url: https://github.com/rerun-io/rerun

extra:
  recipe-maintainers:
    - ruben-arts
    - jleibs
