{% set name = "rerun-sdk" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rerun-io/rerun/archive/refs/tags/{{ version }}.tar.gz
  sha256: 44a96dd20ac0b42d21a76b731490d9623f18f0849583861ede419141b9207e36


build:
  number: 1
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
    # Not using the conda compiler as its version was to low
    - rust >=1.67.1
    - rust-std-wasm32-unknown-unknown
    - semver >=2.13,<2.14
    - wheel >=0.38,<0.39
    - pytest
    - maturin >=0.14,<0.15
    - binaryen
  host:
    - pip
    - python
  run:
    - python
    - pyarrow ==10.0.1
    - deprecated
    - numpy >=1.23
    - pillow >=9.5.0,<10
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("11") }}  # [osx]

test:
  imports:
    - rerun_sdk
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.rerun.io/
  summary: Rerun is an SDK for logging computer vision and robotics data paired with a visualizer for exploring that data over time.
  description: |
    Rerun is an SDK for logging computer vision and robotics data paired with a visualizer for exploring that data over time. 
    It lets you debug and understand the internal state and data of your systems with minimal code.
  license: MIT OR Apache-2.0
  license_file:
    - THIRDPARTY.yml 
    - LICENSE-MIT
    - LICENSE-APACHE

  doc_url: https://www.rerun.io/docs
  dev_url: https://github.com/rerun-io/rerun

extra:
  recipe-maintainers:
    - ruben-arts
    - jleibs
