{% set name = "rerun-sdk" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rerun-io/rerun/archive/refs/tags/{{ version }}.tar.gz
  sha256: a949aa7b941053d4ce7d241b5471d5ef3a10c59d759b40f3d07a6a13872b381f

build:
  number: 0
  skip: true  # [py<38]
  entry_points:
    - rerun = rerun.__main__:main

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - crossenv                               # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - maturin >=0.14,<0.15                   # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses
    # Not using the conda compiler as its version was to low
    - rust >=1.67.1
    - rust-std-wasm32-unknown-unknown
    {% if target_platform == "osx-arm64" %}
    - rust-std-aarch64-apple-darwin
    {% endif %}
    # binaryen gives us wasm-opt, for optimizing the an .wasm file for speed and size
    - binaryen
  host:
    - python
    - pip
    - maturin >=0.14,<0.15
  run:
    - python
    - attrs >=23.1.0
    - numpy >=1.23
    - pillow
    - pyarrow ==10.0.1
    - typing_extensions >=4.5
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("11") }}  # [osx]

test:
  imports:
    - rerun_sdk
  requires:
    - pip
  commands:
    - pip check
    - rerun --version

about:
  home: https://www.rerun.io/
  summary: Rerun is an SDK for logging computer vision and robotics data paired with a visualizer for exploring that data over time.
  description: |
    Rerun is an SDK for logging computer vision and robotics data paired with a visualizer for exploring that data over time. 
    It lets you debug and understand the internal state and data of your systems with minimal code.
  license: MIT OR Apache-2.0
  license_file:
    - THIRDPARTY.yml
    - LICENSE-MIT
    - LICENSE-APACHE

  doc_url: https://www.rerun.io/docs
  dev_url: https://github.com/rerun-io/rerun

extra:
  recipe-maintainers:
    - ruben-arts
    - jleibs
